/**
 * Placeholder-document generator for the UAT scenario seed (#88, seed-matrix §0).
 *
 * The seeded vendors reference real uploaded bytes: a tester who clicks "view" on vendor 1's NPWP
 * must get a document, not a broken viewer. Those bytes have to come from somewhere, and shipping
 * binary fixtures in the repo would mean ~90 opaque blobs nobody can diff — so they are *generated*
 * here instead, one tiny valid PDF per document, captioned with what it stands in for.
 *
 * Deliberately hand-rolled rather than pulled from a PDF library: the whole requirement is "a few
 * hundred bytes a browser will render", and a real generator would be a production dependency added
 * for fixtures alone. The output is a minimal but **spec-correct** PDF — the cross-reference table
 * carries true byte offsets, so viewers that validate it (rather than repairing it) still open it.
 */

/**
 * PDF string literals are parenthesised, so `(`, `)` and `\` must be escaped or the object breaks.
 * Non-ASCII is dropped rather than escaped: the base-14 Helvetica we reference has no reliable glyph
 * coverage beyond ASCII, and a byte-length/character-length mismatch would corrupt `/Length` below.
 */
const pdfText = (value: string): string =>
  value.replace(/[^\x20-\x7E]/g, "?").replace(/([\\()])/g, "\\$1");

/** A page's worth of text drawing operators — a title line plus body lines down the page. */
const contentStream = (title: string, lines: readonly string[]): string =>
  [
    `BT /F1 18 Tf 60 780 Td (${pdfText(title)}) Tj ET`,
    ...lines.map((line, i) => `BT /F1 11 Tf 60 ${744 - i * 18} Td (${pdfText(line)}) Tj ET`),
  ].join("\n");

/** What every generated fixture says on it, so a tester never mistakes one for a real certificate. */
export const PLACEHOLDER_NOTICE =
  "Placeholder document generated by the VMS UAT seed. Not a real certificate.";

/**
 * Build a one-page PDF captioned with `title` and `lines`. Returns the encoded bytes ready for
 * storage. Pure and deterministic — the same arguments always produce byte-identical output, which
 * is what lets the seed re-run without churning objects in MinIO.
 */
export const placeholderPdf = (title: string, lines: readonly string[]): Uint8Array => {
  const content = contentStream(title, [...lines, "", PLACEHOLDER_NOTICE]);
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] " +
      "/Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`,
  ];

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [];
  for (const [i, body] of objects.entries()) {
    offsets.push(pdf.length);
    pdf += `${i + 1} 0 obj\n${body}\nendobj\n`;
  }

  // The xref table must record each object's true byte offset from the file start — hence building
  // the body first and measuring as we go, rather than templating the whole file in one string.
  const startXref = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets) pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${startXref}\n%%EOF\n`;

  return new TextEncoder().encode(pdf);
};
